
on:
    release:
      types: [created]
    push:
      branches: [ "main" ]

permissions:
      contents: write
      packages: write
  
jobs:
    releases-matrix:
      name: Release Go Binary
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux, windows, darwin]
          goarch: ["386", amd64, arm64, arm]
          exclude:
            - goarch: "386"
              goos: darwin
            - goarch: "arm"
              goos: darwin
      steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: bash build.sh
